name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
    workflow_dispatch:
    pull_request:
        types: [closed]
        branches:
            - main
        
jobs:
    deployment:
        name: Deploy
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        runs-on: 'ubuntu-latest'
        environment:
            name: production
            url: atprotofeed.firebot.app/.well-known/did.json
        steps:
            - name: SSH Remote Commands
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: cd /srv/firebot-atproto-feed-generator/ && git reset --hard origin/main && git pull && npm install && npm run build
